---
title: "Ziqi Wang's website"
---

### Research

Recently I have been studying whether the biodiversity of bird species is affected by different ecological environments.

My team members and I determined the situation of bird populations in different ecological environments by comparing the number and species diversity of birds in natural ecological environments (national parks) and artificial ecological environments (campus). My team members and I were divided into two groups. One group was responsible for observing and recording the types and numbers of birds on campus. The other group went to the national park to observe and record the types and numbers of birds. We determine the bird's species by using an App (iNaturalist). We conducted a month-long observation to finally determine the relationship between the number and diversity of birds in artificial ecological environments and natural ecological environments.



<br />
<br />
<br />
<br />

# Contact Information

**Name:** Ziqi Wang

**Email:** zw2977@cumc.columbia.edu

**Phone:** 5136179718

**Address:**
45 Tiemann Pl, New York, NY 10027
